server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#---
#spring:
#  profiles: peer1
#  application:
#    name: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    serviceUrl:
#      defaultZone: http://peer2:8762/eureka/
#
#
#---
#spring:
#  profiles: peer2
#  application:
#    name: peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/
