---
spring:
  profiles: eureka-client-1
  application:
    name: eureka-client
eureka:
  instance:
    hostname: eureka-client
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762

---
spring:
  profiles: eureka-client-2
  application:
    name: eureka-client
eureka:
  instance:
    hostname: eureka-client
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763